[2021-04-28 11:37:44,569] - logger.py] - INFO: test_01_login_success
[2021-04-28 11:46:45,937] - logger.py] - INFO: 用例test_01_login_success测试通过
[2021-04-28 11:47:20,832] - logger.py] - INFO: ------------测试完成生成测试报告---------------




[2021-04-28 12:11:40,499] - logger.py] - INFO: 用例test_01_login_success测试通过
[2021-04-28 12:12:00,098] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 12:12:19,274] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 12:12:37,166] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 12:13:34,567] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 12:13:49,264] - logger.py] - INFO: 用例test_01_login_success测试通过
[2021-04-28 12:14:05,354] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 12:14:19,597] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 12:14:35,221] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 12:14:40,496] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:07:41,599] - logger.py] - INFO: 用例test_01_login_success测试通过
[2021-04-28 13:09:01,392] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:09:41,092] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:10:25,696] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:10:39,261] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:10:53,001] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:10:57,665] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:13:25,345] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:14:05,342] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:14:45,428] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:15:25,627] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:16:10,051] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:16:22,675] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:16:35,608] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:16:40,464] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:17:36,022] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:18:15,911] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:19:00,743] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:19:13,909] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:19:26,873] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:19:31,567] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:21:25,541] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:22:05,079] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:22:49,619] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:23:03,296] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:23:16,592] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:23:21,854] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:24:36,651] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:25:16,628] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:26:01,849] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:26:14,566] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:26:28,315] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:26:32,967] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:28:22,280] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:29:02,714] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:29:46,661] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:29:59,848] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:30:14,328] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:30:18,949] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:37:48,645] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:38:31,499] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:39:17,827] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:39:32,349] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:39:46,279] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:39:51,533] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:43:45,288] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:44:27,147] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:45:21,095] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:45:37,687] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:45:53,993] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:45:59,396] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 13:52:07,806] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 13:52:51,964] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 13:53:39,286] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:53:57,393] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:54:12,059] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 13:54:16,760] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 14:05:12,919] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 14:05:54,348] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 14:06:41,138] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:06:55,794] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:07:10,078] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:07:15,036] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 14:29:15,996] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 14:34:31,240] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 14:35:12,392] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 14:35:58,636] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:36:12,588] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:36:26,349] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:36:30,915] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 14:38:47,916] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 14:39:29,758] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 14:40:15,154] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:40:30,373] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:40:47,042] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 14:40:52,123] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 15:08:29,784] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 15:09:11,888] - logger.py] - INFO: 截取当前屏幕截图:test_01_login_success
[2021-04-28 15:09:11,888] - logger.py] - ERROR: 用例test_01_login_success执行失败
[2021-04-28 15:09:43,071] - logger.py] - INFO: 截取当前屏幕截图:test_01_login_success
[2021-04-28 15:09:58,811] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 15:10:13,632] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 15:10:28,027] - logger.py] - INFO: 用例test_02_login_fail测试通过
[2021-04-28 15:10:32,683] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 15:35:09,027] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 15:35:53,660] - logger.py] - INFO: 截取当前屏幕截图:test_01_login_success
[2021-04-28 15:35:53,663] - logger.py] - ERROR: 用例:test_01_login_success执行失败
[2021-04-28 15:36:40,733] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 15:36:55,460] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 15:37:13,564] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 15:37:18,308] - logger.py] - INFO: ------------测试完成生成测试报告---------------
[2021-04-28 15:46:28,882] - logger.py] - INFO: ------------开始执行所有测试用例---------------
[2021-04-28 15:47:18,890] - logger.py] - INFO: 截取当前屏幕截图:test_01_login_success
[2021-04-28 15:47:18,891] - logger.py] - ERROR: 用例:test_01_login_success执行失败
[2021-04-28 15:48:05,211] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 16:32:22,410] - logger.py] - INFO: 截取当前屏幕截图:test_01_login_success
[2021-04-28 16:32:22,411] - logger.py] - ERROR: 用例:test_01_login_success执行失败
[2021-04-28 16:33:19,412] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 16:33:38,306] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 16:33:57,359] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 16:36:53,662] - logger.py] - INFO: 截取当前屏幕截图:test_01_login_success
[2021-04-28 16:36:53,662] - logger.py] - ERROR: 用例:test_01_login_success执行失败
[2021-04-28 16:37:44,782] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 16:38:04,630] - logger.py] - INFO: 用例:test_02_login_fail测试通过
[2021-04-28 16:38:28,170] - logger.py] - INFO: 用例:test_02_login_fail测试通过
